name: pixel_bakery_home_web_flutter
description: Pixel Bakery Home Web UI recreated from design
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  excel: ^4.0.6
  file_picker: ^8.1.2
  go_router: ^14.2.7
  http: ^1.2.2
  shared_preferences: ^2.3.2
  universal_html: ^2.2.4
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
